import type { Category, Product } from "@/types";

// Using Picsum for reliable placeholder images
export const MOCK_CATEGORIES: Category[] = [
  {
    id: "1",
    name: "Rosas",
    slug: "rosas",
    description: "Hermosas rosas para toda ocasión",
    imageUrl: "https://picsum.photos/seed/roses/600/400",
    parentId: null,
    isActive: true,
    displayOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Girasoles",
    slug: "girasoles",
    description: "Brillantes girasoles que alegran cualquier día",
    imageUrl: "https://picsum.photos/seed/sunflowers/600/400",
    parentId: null,
    isActive: true,
    displayOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Tulipanes",
    slug: "tulipanes",
    description: "Elegantes tulipanes de diversos colores",
    imageUrl: "https://picsum.photos/seed/tulips/600/400",
    parentId: null,
    isActive: true,
    displayOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Orquídeas",
    slug: "orquideas",
    description: "Exóticas orquídeas de alta calidad",
    imageUrl: "https://picsum.photos/seed/orchids/600/400",
    parentId: null,
    isActive: true,
    displayOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Arreglos Mixtos",
    slug: "arreglos-mixtos",
    description: "Combinaciones únicas de flores variadas",
    imageUrl: "https://picsum.photos/seed/mixed/600/400",
    parentId: null,
    isActive: true,
    displayOrder: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Ocasiones Especiales",
    slug: "ocasiones-especiales",
    description: "Arreglos para momentos únicos",
    imageUrl: "https://picsum.photos/seed/special/600/400",
    parentId: null,
    isActive: true,
    displayOrder: 6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Ramo de 12 Rosas Rojas",
    slug: "ramo-12-rosas-rojas",
    description: "Clásico ramo de 12 rosas rojas, símbolo de amor eterno.",
    priceCents: 3500,
    comparePriceCents: 4500,
    sku: "ROS-RED-12",
    categoryId: "1",
    isActive: true,
    isFeatured: true,
    isQuickDelivery: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: "img1",
        productId: "1",
        url: "https://picsum.photos/seed/roses12/600/600",
        altText: "Ramo de 12 rosas rojas",
        displayOrder: 0,
        isPrimary: true,
        createdAt: new Date().toISOString(),
      },
    ],
    branchId: null, includesCard: true, cardMessageFeeCents: null, preparationMinutes: 15, inStock: true, availableQuantity: 10, hasRecipe: false, materialCostCents: null, displayPriceCents: 3850, transferPriceCents: 3500,
  },
  {
    id: "2",
    name: "Ramo de 24 Rosas Rojas",
    slug: "ramo-24-rosas-rojas",
    description: "Impresionante ramo de 24 rosas rojas premium.",
    priceCents: 6500,
    comparePriceCents: 7500,
    sku: "ROS-RED-24",
    categoryId: "1",
    isActive: true,
    isFeatured: true,
    isQuickDelivery: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: "img2",
        productId: "2",
        url: "https://picsum.photos/seed/roses24/600/600",
        altText: "Ramo de 24 rosas rojas",
        displayOrder: 0,
        isPrimary: true,
        createdAt: new Date().toISOString(),
      },
    ],
    branchId: null, includesCard: true, cardMessageFeeCents: null, preparationMinutes: 15, inStock: true, availableQuantity: 5, hasRecipe: false, materialCostCents: null, displayPriceCents: 7150, transferPriceCents: 6500,
  },
  {
    id: "3",
    name: "Bouquet de Girasoles",
    slug: "bouquet-girasoles",
    description: "6 girasoles frescos que irradian alegría.",
    priceCents: 2500,
    comparePriceCents: null,
    sku: "GIR-BOU-6",
    categoryId: "2",
    isActive: true,
    isFeatured: true,
    isQuickDelivery: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: "img3",
        productId: "3",
        url: "https://picsum.photos/seed/sunflower6/600/600",
        altText: "Bouquet de girasoles",
        displayOrder: 0,
        isPrimary: true,
        createdAt: new Date().toISOString(),
      },
    ],
    branchId: null, includesCard: true, cardMessageFeeCents: null, preparationMinutes: 15, inStock: true, availableQuantity: 8, hasRecipe: false, materialCostCents: null, displayPriceCents: 4950, transferPriceCents: 4500,
  },
  {
    id: "4",
    name: "Orquídea Phalaenopsis",
    slug: "orquidea-phalaenopsis",
    description: "Elegante orquídea Phalaenopsis en maceta decorativa.",
    priceCents: 5500,
    comparePriceCents: null,
    sku: "ORQ-PHA-01",
    categoryId: "4",
    isActive: true,
    isFeatured: true,
    isQuickDelivery: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: "img4",
        productId: "4",
        url: "https://picsum.photos/seed/orchid1/600/600",
        altText: "Orquídea Phalaenopsis",
        displayOrder: 0,
        isPrimary: true,
        createdAt: new Date().toISOString(),
      },
    ],
    branchId: null, includesCard: true, cardMessageFeeCents: null, preparationMinutes: 20, inStock: true, availableQuantity: 3, hasRecipe: false, materialCostCents: null, displayPriceCents: 8800, transferPriceCents: 8000,
  },
  {
    id: "5",
    name: "Caja de Flores Sorpresa",
    slug: "caja-flores-sorpresa",
    description: "Elegante caja con selección de flores premium.",
    priceCents: 4800,
    comparePriceCents: 5800,
    sku: "MIX-BOX-01",
    categoryId: "5",
    isActive: true,
    isFeatured: true,
    isQuickDelivery: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: "img5",
        productId: "5",
        url: "https://picsum.photos/seed/flowerbox/600/600",
        altText: "Caja de flores sorpresa",
        displayOrder: 0,
        isPrimary: true,
        createdAt: new Date().toISOString(),
      },
    ],
    branchId: null, includesCard: true, cardMessageFeeCents: null, preparationMinutes: 15, inStock: true, availableQuantity: 6, hasRecipe: false, materialCostCents: null, displayPriceCents: 3300, transferPriceCents: 3000,
  },
  {
    id: "6",
    name: "Tulipanes Holandeses",
    slug: "tulipanes-holandeses",
    description: "10 tulipanes importados de Holanda.",
    priceCents: 4500,
    comparePriceCents: 5500,
    sku: "TUL-HOL-10",
    categoryId: "3",
    isActive: true,
    isFeatured: true,
    isQuickDelivery: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: "img6",
        productId: "6",
        url: "https://picsum.photos/seed/tulips10/600/600",
        altText: "Tulipanes holandeses",
        displayOrder: 0,
        isPrimary: true,
        createdAt: new Date().toISOString(),
      },
    ],
    branchId: null, includesCard: true, cardMessageFeeCents: null, preparationMinutes: 15, inStock: true, availableQuantity: 4, hasRecipe: false, materialCostCents: null, displayPriceCents: 5500, transferPriceCents: 5000,
  },
  {
    id: "7",
    name: "Rosas Rosadas Mix",
    slug: "rosas-rosadas-mix",
    description: "Delicado arreglo de rosas en tonos rosados.",
    priceCents: 2800,
    comparePriceCents: null,
    sku: "ROS-PINK-MIX",
    categoryId: "1",
    isActive: true,
    isFeatured: true,
    isQuickDelivery: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: "img7",
        productId: "7",
        url: "https://picsum.photos/seed/pinkroses/600/600",
        altText: "Rosas rosadas mix",
        displayOrder: 0,
        isPrimary: true,
        createdAt: new Date().toISOString(),
      },
    ],
    branchId: null, includesCard: true, cardMessageFeeCents: null, preparationMinutes: 10, inStock: true, availableQuantity: 12, hasRecipe: false, materialCostCents: null, displayPriceCents: 2750, transferPriceCents: 2500,
  },
  {
    id: "8",
    name: "Arreglo Primaveral",
    slug: "arreglo-primaveral",
    description: "Colorida mezcla de flores de temporada.",
    priceCents: 3800,
    comparePriceCents: null,
    sku: "MIX-PRI-01",
    categoryId: "5",
    isActive: true,
    isFeatured: true,
    isQuickDelivery: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      {
        id: "img8",
        productId: "8",
        url: "https://picsum.photos/seed/spring/600/600",
        altText: "Arreglo primaveral",
        displayOrder: 0,
        isPrimary: true,
        createdAt: new Date().toISOString(),
      },
    ],
    branchId: null, includesCard: true, cardMessageFeeCents: null, preparationMinutes: 25, inStock: true, availableQuantity: 7, hasRecipe: false, materialCostCents: null, displayPriceCents: 11000, transferPriceCents: 10000,
  },
];
